<select name="lang" id="lang">
    <option value="en">English | USD</option>
    <option value="pl">Polish (Polski) | PLN</option>
    <option value="de">German (Deutsch) | EUR</option>
    <option value="fr">French (Français) | EUR</option>
    <option value="es">Spanish (Español) | EUR</option>
    <option value="it">Italian (Italiano) | EUR</option>
    <option value="nl">Dutch (Nederlands) | EUR</option>
    <option value="pt">Portuguese (Português) | EUR</option>
    <option value="ru">Russian (Русский) | RUB</option>
    <option value="uk">Ukrainian (Українська) | UAH</option>
    <option value="cz">Czech (Čeština) | CZK</option>
    <option value="sk">Slovak (Slovenčina) | EUR</option>
    <option value="hu">Hungarian (Magyar) | HUF</option>
    <option value="ro">Romanian (Română) | RON</option>
    <option value="bg">Bulgarian (Български) | BGN</option>
    <option value="hr">Croatian (Hrvatski) | EUR</option>
    <option value="sr">Serbian (Српски) | RSD</option>
    <option value="sl">Slovenian (Slovenščina) | EUR</option>
    <option value="lt">Lithuanian (Lietuvių) | EUR</option>
    <option value="lv">Latvian (Latviešu) | EUR</option>
    <option value="ee">Estonian (Eesti) | EUR</option>
    <option value="fi">Finnish (Suomi) | EUR</option>
    <option value="se">Swedish (Svenska) | SEK</option>
    <option value="no">Norwegian (Norsk) | NOK</option>
    <option value="dk">Danish (Dansk) | DKK</option>
    <option value="is">Icelandic (Íslenska) | ISK</option>
    <option value="gr">Greek (Ελληνικά) | EUR</option>
    <option value="tr">Turkish (Türkçe) | TRY</option>
    <option value="jp">Japanese (日本語) | JPY</option>
    <option value="kr">Korean (한국어) | KRW</option>
    <option value="cn">Chinese (中文) | CNY</option>
    <option value="tw">Taiwanese (繁體中文) | TWD</option>
    <option value="hk">Hong Kong (香港) | HKD</option>
    <option value="in">Hindi (हिन्दी) | INR</option>
    <option value="ar">Arabic (العربية) | SAR</option>
    <option value="il">Hebrew (עברית) | ILS</option>
    <option value="th">Thai (ไทย) | THB</option>
    <option value="id">Indonesian (Bahasa Indonesia) | IDR</option>
    <option value="ph">Filipino (Filipino) | PHP</option>
    <option value="vn">Vietnamese (Tiếng Việt) | VND</option>
    <option value="au">Australian (English) | AUD</option>
    <option value="nz">New Zealand (English) | NZD</option>
    <option value="za">South African (English) | ZAR</option>
    <option value="mx">Mexican (Español) | MXN</option>
    <option value="br">Brazilian (Português) | BRL</option>
    <option value="ca">Canadian (English/French) | CAD</option>
    <option value="ch">Swiss (Deutsch/Français/Italiano) | CHF</option>
</select>